name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
          cache: yarn

      - name: Install
        run: yarn

      - name: Run Build
        run: yarn build --configuration production

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist/accessibility-maze'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: ${{ github.ref == 'refs/heads/main' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
